//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mytour.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pthuc_tt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pthuc_tt()
        {
            this.Thanh_toan = new HashSet<Thanh_toan>();
        }
    
        public string ma_pt_tt { get; set; }
        public string loai_thanh_toan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Thanh_toan> Thanh_toan { get; set; }
    }
}
